### ISSUE TITLE
Why is SummarizedExperiment graphic not directly included in package?

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/SummarizedExperiment#24]
Is there a reason the graphic describing the geometry of the *SummarizedExperiment* class is not included in in the package?
Instead, it's downloaded from a Google Doc and then included in the vignette
https://github.com/Bioconductor/SummarizedExperiment/blob/01aa07a87b72b7423bea38028fffba4e896fdcf3/vignettes/SummarizedExperiment.Rmd#L75
I'm including this figure in a workflow and it felt odd to have to download a file from a random looking URL rather than include it via `system.file()` from the package.

**Comment by mtmorgan** [comment]
I think this was a convenience when the figure was changing rapidly. It would be natural to add the file as vignettes/SE.svg, but actually that wouldn't give `system.file()`access since it is not in the installed package. You'd still need to download the file from a url, but at least it wouldn't be quite so random?

**Comment by PeteHaitch** [comment]
Ah, I'd not understood that files in `vignettes/` aren't installed.
I guess then my query becomes: what should be the canonical source for this figure to enable its reuse?
The 'random' URL feels a bit odd for such a useful graphic of a central Bioconductor class.

**Comment by mtmorgan** [comment]
It should be available (after 1.15.3 propagates) as `system.file(package="SummarizedExpeirment", "doc", "SE.svg")`

**Comment by PeteHaitch** [comment]
Thanks Martin!
